const express = require('express');
const { requireCaisseAccess } = require('./caisse');
const { InputError } = require('./crm-data');
const clean = (value, max = 500) => typeof value === 'string' ? value.trim().replace(/\s+/g, ' ').slice(0, max) : '';
const idFor = value => { const id = Number(value); if (!Number.isSafeInteger(id) || id < 1) throw new InputError('Identifiant invalide.'); return id; };
const hex = value => /^#[0-9a-f]{6}$/i.test(value || '');
const email = value => !value || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const siret = value => !value || /^\d{14}$/.test(value);
const cents = value => { const n = Number(value); if (!Number.isSafeInteger(n) || n < 0 || n > 1000000000) throw new InputError('Montant invalide.'); return n; };
async function transaction(pool, work) { const c = await pool.getConnection(); try { await c.beginTransaction(); const result = await work(c); await c.commit(); return result; } catch (error) { await c.rollback().catch(() => {}); throw error; } finally { c.release(); } }
function companyInput(body) {
 const data = { legalName: clean(body.legalName, 200), siret: clean(body.siret, 14), vatNumber: clean(body.vatNumber, 32), address: clean(body.address), email: clean(body.email, 254), phone: clean(body.phone, 40), iban: clean(body.iban, 34).replace(/\s/g, ''), paymentTerms: clean(body.paymentTerms) };
 if (!siret(data.siret) || !email(data.email) || (data.iban && !/^[A-Z]{2}[0-9A-Z]{13,32}$/i.test(data.iban))) throw new InputError('Les coordonnées de facturation sont invalides.'); return data;
}
function templateInput(body) { const data = { name: clean(body.name, 100), logoUrl: clean(body.logoUrl), primaryColor: clean(body.primaryColor, 7), accentColor: clean(body.accentColor, 7), footer: clean(body.footer, 1000) }; if (!data.name || !hex(data.primaryColor) || !hex(data.accentColor) || (data.logoUrl && !/^https:\/\//i.test(data.logoUrl))) throw new InputError('Modèle de facture invalide. Utilisez une URL de logo HTTPS et des couleurs hexadécimales.'); return data; }
function customerInput(body) { const data = { companyName: clean(body.companyName, 200), siret: clean(body.siret, 14), vatNumber: clean(body.vatNumber, 32), billingAddress: clean(body.billingAddress), invoiceEmail: clean(body.invoiceEmail, 254), electronicAddress: clean(body.electronicAddress, 254) }; if (!siret(data.siret) || !email(data.invoiceEmail) || !email(data.electronicAddress)) throw new InputError('Coordonnées professionnelles invalides.'); return data; }
function draftInput(body) { const label = clean(body.label, 200); const lines = Array.isArray(body.lines) ? body.lines : []; if (!label || !lines.length || lines.length > 100) throw new InputError('Ajoutez un libellé et entre 1 et 100 lignes.'); const normalized = lines.map(line => { const description = clean(line.description, 250), quantity = Number(line.quantity), unitCents = cents(line.unitCents), taxBps = Number(line.taxBps); if (!description || !Number.isInteger(quantity) || quantity < 1 || quantity > 10000 || ![0, 550, 1000, 2000].includes(taxBps)) throw new InputError('Ligne de facture invalide.'); const grossCents = quantity * unitCents, taxCents = Math.floor((grossCents * taxBps + (10000 + taxBps) / 2) / (10000 + taxBps)); return { description, quantity, unitCents, taxBps, grossCents, taxCents, netCents: grossCents - taxCents }; }); const totals = normalized.reduce((sum, line) => ({ grossCents: sum.grossCents + line.grossCents, netCents: sum.netCents + line.netCents, taxCents: sum.taxCents + line.taxCents }), { grossCents: 0, netCents: 0, taxCents: 0 }); if (totals.grossCents > 1000000000) throw new InputError('Total maximal dépassé.'); return { label, lines: normalized, totals, dueDate: /^\d{4}-\d{2}-\d{2}$/.test(body.dueDate || '') ? body.dueDate : null }; }
function createInvoiceRouter(deps) {
 const router = express.Router(); router.use(requireCaisseAccess(deps)); router.use((req, res, next) => { res.set('Cache-Control', 'no-store'); if (!deps.limitRequest(`invoice:${req.session.userId}`, 120, 60000)) return res.sendStatus(429); next(); }); router.use((req, res, next) => req.method === 'GET' ? next() : deps.requireSameOrigin(req, res, next)); router.use(express.json({ limit: '64kb' })); const wrap = fn => async (req,res,next) => { try { await fn(req,res,await deps.getPool(),req.session.userId); } catch(error) { next(error); } };
 router.get('/data', wrap(async (req,res,pool,userId) => { const [companies, templates, customers, profiles, drafts] = await Promise.all([pool.query('SELECT legal_name, siret, vat_number, address, email, phone, iban, payment_terms FROM invoice_company_profiles WHERE id_user=?',[userId]), pool.query('SELECT id, name, logo_url, primary_color, accent_color, footer, is_default, version FROM invoice_templates WHERE id_user=? ORDER BY is_default DESC, id DESC LIMIT 101',[userId]), pool.query('SELECT id,name,email,address FROM crm_customers WHERE id_user=? ORDER BY name LIMIT 1001',[userId]), pool.query('SELECT customer_id,company_name,siret,vat_number,billing_address,invoice_email,electronic_address,version FROM invoice_customer_profiles WHERE id_user=?',[userId]), pool.query('SELECT id,customer_id,template_id,label,data,version,updated_at FROM invoice_drafts WHERE id_user=? ORDER BY updated_at DESC LIMIT 101',[userId])]); res.json({ company: companies[0] || null, templates, customers: customers.map(customer => ({ ...customer, profile: profiles.find(profile => Number(profile.customer_id) === Number(customer.id)) || null })), drafts: drafts.map(draft => ({ ...draft, data: typeof draft.data === 'string' ? JSON.parse(draft.data) : draft.data })) }); }));
 router.post('/company', wrap(async (req,res,pool,userId) => { const data=companyInput(req.body); await pool.query('INSERT INTO invoice_company_profiles (id_user,legal_name,siret,vat_number,address,email,phone,iban,payment_terms) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE legal_name=VALUES(legal_name),siret=VALUES(siret),vat_number=VALUES(vat_number),address=VALUES(address),email=VALUES(email),phone=VALUES(phone),iban=VALUES(iban),payment_terms=VALUES(payment_terms)',[userId,...Object.values(data)]); res.json({ok:true}); }));
 router.post('/templates', wrap(async (req,res,pool,userId) => { const data=templateInput(req.body); const id=req.body.id == null ? null : idFor(req.body.id); if (id) { const r=await pool.query('UPDATE invoice_templates SET name=?,logo_url=?,primary_color=?,accent_color=?,footer=?,version=version+1 WHERE id=? AND id_user=? AND version=?',[...Object.values(data),id,userId,Number(req.body.version)]); if (!r.affectedRows) throw new InputError('Ce modèle a changé. Actualisez avant de modifier.',409); } else { await transaction(pool, async c => { await c.query('UPDATE invoice_templates SET is_default=0 WHERE id_user=?',[userId]); await c.query('INSERT INTO invoice_templates (id_user,name,logo_url,primary_color,accent_color,footer,is_default) VALUES (?,?,?,?,?,?,1)',[userId,...Object.values(data)]); }); } res.json({ok:true}); }));
 router.post('/customers/:id/profile', wrap(async (req,res,pool,userId) => { const customerId=idFor(req.params.id), data=customerInput(req.body); const own=await pool.query('SELECT id FROM crm_customers WHERE id=? AND id_user=?',[customerId,userId]); if (!own.length) throw new InputError('Cliente introuvable.',404); await pool.query('INSERT INTO invoice_customer_profiles (customer_id,id_user,company_name,siret,vat_number,billing_address,invoice_email,electronic_address) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE company_name=VALUES(company_name),siret=VALUES(siret),vat_number=VALUES(vat_number),billing_address=VALUES(billing_address),invoice_email=VALUES(invoice_email),electronic_address=VALUES(electronic_address),version=version+1',[customerId,userId,...Object.values(data)]); res.json({ok:true}); }));
 router.post('/drafts', wrap(async (req,res,pool,userId) => { const draft=draftInput(req.body), customerId=idFor(req.body.customerId), templateId=idFor(req.body.templateId); const [customer, template] = await Promise.all([pool.query('SELECT c.id,c.name,c.email,c.address,p.company_name,p.siret,p.vat_number,p.billing_address,p.invoice_email,p.electronic_address FROM crm_customers c LEFT JOIN invoice_customer_profiles p ON p.customer_id=c.id AND p.id_user=c.id_user WHERE c.id=? AND c.id_user=?',[customerId,userId]),pool.query('SELECT id,name,logo_url,primary_color,accent_color,footer FROM invoice_templates WHERE id=? AND id_user=?',[templateId,userId])]); if (!customer.length || !template.length) throw new InputError('Cliente ou modèle introuvable.',404); const snapshot={ ...draft, customer:customer[0], template:template[0], createdFor:'invoice-draft-v1' }; const r=await pool.query('INSERT INTO invoice_drafts (id_user,customer_id,template_id,label,data) VALUES (?,?,?,?,?)',[userId,customerId,templateId,draft.label,JSON.stringify(snapshot)]); res.status(201).json({id:Number(r.insertId), data:snapshot}); }));
 router.use((error,req,res,next) => { if(res.headersSent) return next(error); res.status(error.status||503).json({error:error instanceof InputError?error.message:error.code==='ER_NO_SUCH_TABLE'?'Appliquez la migration 022 dans la base GlowStock pour activer la préparation des factures.':'Impossible de préparer la facture.'}); }); return router;
}
module.exports = { createInvoiceRouter, companyInput, templateInput, customerInput, draftInput };
