const express = require('express');
const crypto = require('node:crypto');
const { InputError } = require('./crm-data');
const gifts = require('./gift-cards');
const { createGiftCardRouter } = require('./gift-card-api');
const idFor = value => { const id=Number(value); if(!Number.isSafeInteger(id)||id<1) throw new InputError('Identifiant invalide.'); return id; };
const money = value => { const text=String(value??'').trim().replace(',','.'); if(!/^\d{1,5}(?:\.\d{1,2})?$/.test(text)) throw new InputError('Montant invalide.'); return Number(text.split('.')[0])*100+Number((text.split('.')[1]||'').padEnd(2,'0')); };
const text = (v,max,required=false) => { const s=typeof v==='string'?v.trim():''; if(s.length>max||(required&&!s)) throw new InputError('Champ invalide.'); return s; };
async function transaction(pool, work){const c=await pool.getConnection();try{await c.beginTransaction();const r=await work(c);await c.commit();return r}catch(e){await c.rollback().catch(()=>{});throw e}finally{c.release()}}
async function applyRealSale(pool,{userId,customerId,saleId,grossCents}){if(process.env.CAISSE_MODE!=='production')throw new InputError('La fidélité automatique est bloquée tant que la caisse n’est pas en production.',409);if(!Number.isSafeInteger(grossCents)||grossCents<0||typeof saleId!=='string'||!saleId)throw new InputError('Encaissement invalide.');return transaction(pool,async c=>{const settings=await c.query('SELECT is_enabled,points_per_euro FROM loyalty_settings WHERE id_user=? FOR UPDATE',[userId]);if(!settings[0]?.is_enabled)return {awarded:0};const key=crypto.createHash('sha256').update(`sale:${userId}:${saleId}`).digest('hex'),prior=await c.query('SELECT points_delta FROM loyalty_ledger WHERE id_user=? AND operation_key=?',[userId,key]);if(prior.length)return {awarded:Number(prior[0].points_delta),replayed:true};const own=await c.query('SELECT id FROM crm_customers WHERE id=? AND id_user=? FOR UPDATE',[customerId,userId]);if(!own.length)throw new InputError('Cliente introuvable.',404);await c.query('INSERT IGNORE INTO loyalty_accounts (customer_id,id_user,balance_points) VALUES (?,?,0)',[customerId,userId]);const account=await c.query('SELECT balance_points FROM loyalty_accounts WHERE customer_id=? FOR UPDATE',[customerId]);const points=Math.floor(grossCents*Number(settings[0].points_per_euro)/100),after=Number(account[0].balance_points)+points;await c.query('UPDATE loyalty_accounts SET balance_points=? WHERE customer_id=?',[after,customerId]);await c.query('INSERT INTO loyalty_ledger (id,id_user,customer_id,operation_key,operation_type,points_delta,balance_after,reason) VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),userId,customerId,key,'real_sale_award',points,after,`Encaissement ${saleId}`]);return {awarded:points}})}
async function access(req,deps){const id=req.session?.userId;if(!id)throw new InputError('Session expirée.',401);if(!(await deps.hasPermission(id,'manage_products'))||(await deps.getSubscriptionStatus(id)).level!=='full')throw new InputError('Accès refusé.',403);return id}
function createRouter(deps){const r=express.Router();r.use(async(req,res,next)=>{try{req.loyaltyUserId=await access(req,deps);res.set({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});if(deps.limitRequest&&!deps.limitRequest(`loyalty:${req.loyaltyUserId}`,120,60000))throw new InputError('Trop de demandes. Réessayez dans un instant.',429);next()}catch(e){next(e)}});r.use((req,res,next)=>['GET','HEAD'].includes(req.method)?next():deps.requireSameOrigin(req,res,next));r.use(express.json({limit:'4kb'}));r.use(createGiftCardRouter(deps));
r.get('/data',async(req,res,next)=>{try{const p=await deps.getPool(),u=req.loyaltyUserId,[settings,cards]=await Promise.all([p.query('SELECT * FROM loyalty_settings WHERE id_user=?',[u]),gifts.listCards(p,u)]);res.json({settings:settings[0]||null,cards})}catch(e){next(e)}});
r.post('/settings',async(req,res,next)=>{try{const b=req.body||{},a=[Number(b.pointsPerEuro),Number(b.rewardPoints),money(b.rewardAmount),b.expiresAfterDays===''||b.expiresAfterDays==null?null:Number(b.expiresAfterDays)];if(a.some((v,i)=>i===3?v!==null&&(!Number.isInteger(v)||v<1||v>3650):!Number.isInteger(v)||v<1||v>(i===2?1000000:100000)))throw new InputError('Paramètres de fidélité invalides.');await (await deps.getPool()).query('INSERT INTO loyalty_settings (id_user,is_enabled,points_per_euro,reward_points,reward_cents,expires_after_days) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE is_enabled=VALUES(is_enabled),points_per_euro=VALUES(points_per_euro),reward_points=VALUES(reward_points),reward_cents=VALUES(reward_cents),expires_after_days=VALUES(expires_after_days)',[req.loyaltyUserId,b.enabled===true?1:0,...a]);res.json({ok:true})}catch(e){next(e)}});
r.get('/customers/:id',async(req,res,next)=>{try{const customer=idFor(req.params.id),p=await deps.getPool(),u=req.loyaltyUserId;const [own,account,ledger]=await Promise.all([p.query('SELECT id FROM crm_customers WHERE id=? AND id_user=?',[customer,u]),p.query('SELECT balance_points FROM loyalty_accounts WHERE customer_id=? AND id_user=?',[customer,u]),p.query('SELECT operation_type,points_delta,balance_after,reason,created_at FROM loyalty_ledger WHERE customer_id=? AND id_user=? ORDER BY created_at DESC LIMIT 101',[customer,u])]);if(!own.length)throw new InputError('Cliente introuvable.',404);res.json({balancePoints:Number(account[0]?.balance_points||0),ledger})}catch(e){next(e)}});
r.post('/customers/:id/adjust',async(req,res,next)=>{try{const customer=idFor(req.params.id),delta=Number(req.body?.points),reason=text(req.body?.reason,500,true);if(!Number.isInteger(delta)||!delta||Math.abs(delta)>100000)throw new InputError('Ajustement invalide.');const key=crypto.createHash('sha256').update(`${req.loyaltyUserId}:${customer}:${crypto.randomUUID()}`).digest('hex');await transaction(await deps.getPool(),async c=>{const own=await c.query('SELECT id FROM crm_customers WHERE id=? AND id_user=? FOR UPDATE',[customer,req.loyaltyUserId]);if(!own.length)throw new InputError('Cliente introuvable.',404);await c.query('INSERT IGNORE INTO loyalty_accounts (customer_id,id_user,balance_points) VALUES (?,?,0)',[customer,req.loyaltyUserId]);const a=await c.query('SELECT balance_points FROM loyalty_accounts WHERE customer_id=? AND id_user=? FOR UPDATE',[customer,req.loyaltyUserId]);const after=Number(a[0].balance_points)+delta;if(after<0)throw new InputError('Le solde ne peut pas devenir négatif.',409);await c.query('UPDATE loyalty_accounts SET balance_points=? WHERE customer_id=?',[after,customer]);await c.query('INSERT INTO loyalty_ledger (id,id_user,customer_id,operation_key,operation_type,points_delta,balance_after,reason) VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),req.loyaltyUserId,customer,key,'manual_adjustment',delta,after,reason])});res.json({ok:true})}catch(e){next(e)}});
r.use((e,req,res,next)=>{if(res.headersSent)return next(e);const status=e instanceof InputError?e.status:e.type==='entity.too.large'?413:e.type==='entity.parse.failed'?400:503;res.status(status).json({error:e instanceof InputError?e.message:status===400?'JSON invalide.':status===413?'Demande trop volumineuse.':['ER_NO_SUCH_TABLE','ER_BAD_FIELD_ERROR'].includes(e.code)?'Appliquez les migrations 027 et 028 dans la base GlowStock.':'Opération fidélité impossible.'})});return r}
module.exports={createRouter,money,applyRealSale};
