const express = require('express');
const crypto = require('node:crypto');
const { InputError } = require('./crm-data');
const idFor = value => { const id=Number(value); if(!Number.isSafeInteger(id)||id<1) throw new InputError('Identifiant invalide.'); return id; };
const money = value => { const text=String(value??'').trim().replace(',','.'); if(!/^\d{1,5}(?:\.\d{1,2})?$/.test(text)) throw new InputError('Montant invalide.'); return Number(text.split('.')[0])*100+Number((text.split('.')[1]||'').padEnd(2,'0')); };
const text = (v,max,required=false) => { const s=typeof v==='string'?v.trim():''; if(s.length>max||(required&&!s)) throw new InputError('Champ invalide.'); return s; };
async function transaction(pool, work){const c=await pool.getConnection();try{await c.beginTransaction();const r=await work(c);await c.commit();return r}catch(e){await c.rollback().catch(()=>{});throw e}finally{c.release()}}
async function access(req,deps){const id=req.session?.userId;if(!id)throw new InputError('Session expirée.',401);if(!(await deps.hasPermission(id,'manage_products'))||(await deps.getSubscriptionStatus(id)).level!=='full')throw new InputError('Accès refusé.',403);return id}
function createRouter(deps){const r=express.Router();r.use(express.json({limit:'4kb'}));r.use(async(req,res,next)=>{try{req.loyaltyUserId=await access(req,deps);res.set('Cache-Control','no-store');next()}catch(e){next(e)}});r.use((req,res,next)=>req.method==='GET'?next():deps.requireSameOrigin(req,res,next));
r.get('/data',async(req,res,next)=>{try{const p=await deps.getPool(),u=req.loyaltyUserId,[settings,cards]=await Promise.all([p.query('SELECT * FROM loyalty_settings WHERE id_user=?',[u]),p.query('SELECT id,code,initial_cents,balance_cents,expires_at,status,created_at FROM gift_cards WHERE id_user=? ORDER BY created_at DESC LIMIT 101',[u])]);res.json({settings:settings[0]||null,cards})}catch(e){next(e)}});
r.post('/settings',async(req,res,next)=>{try{const b=req.body||{},a=[Number(b.pointsPerEuro),Number(b.rewardPoints),money(b.rewardAmount),b.expiresAfterDays===''||b.expiresAfterDays==null?null:Number(b.expiresAfterDays)];if(a.some((v,i)=>i===3?v!==null&&(!Number.isInteger(v)||v<1||v>3650):!Number.isInteger(v)||v<1||v>(i===2?1000000:100000)))throw new InputError('Paramètres de fidélité invalides.');await (await deps.getPool()).query('INSERT INTO loyalty_settings (id_user,is_enabled,points_per_euro,reward_points,reward_cents,expires_after_days) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE is_enabled=VALUES(is_enabled),points_per_euro=VALUES(points_per_euro),reward_points=VALUES(reward_points),reward_cents=VALUES(reward_cents),expires_after_days=VALUES(expires_after_days)',[req.loyaltyUserId,b.enabled===true?1:0,...a]);res.json({ok:true})}catch(e){next(e)}});
r.get('/customers/:id',async(req,res,next)=>{try{const customer=idFor(req.params.id),p=await deps.getPool(),u=req.loyaltyUserId;const [own,account,ledger]=await Promise.all([p.query('SELECT id FROM crm_customers WHERE id=? AND id_user=?',[customer,u]),p.query('SELECT balance_points FROM loyalty_accounts WHERE customer_id=? AND id_user=?',[customer,u]),p.query('SELECT operation_type,points_delta,balance_after,reason,created_at FROM loyalty_ledger WHERE customer_id=? AND id_user=? ORDER BY created_at DESC LIMIT 101',[customer,u])]);if(!own.length)throw new InputError('Cliente introuvable.',404);res.json({balancePoints:Number(account[0]?.balance_points||0),ledger})}catch(e){next(e)}});
r.post('/customers/:id/adjust',async(req,res,next)=>{try{const customer=idFor(req.params.id),delta=Number(req.body?.points),reason=text(req.body?.reason,500,true);if(!Number.isInteger(delta)||!delta||Math.abs(delta)>100000)throw new InputError('Ajustement invalide.');const key=crypto.createHash('sha256').update(`${req.loyaltyUserId}:${customer}:${crypto.randomUUID()}`).digest('hex');await transaction(await deps.getPool(),async c=>{const own=await c.query('SELECT id FROM crm_customers WHERE id=? AND id_user=? FOR UPDATE',[customer,req.loyaltyUserId]);if(!own.length)throw new InputError('Cliente introuvable.',404);await c.query('INSERT IGNORE INTO loyalty_accounts (customer_id,id_user,balance_points) VALUES (?,?,0)',[customer,req.loyaltyUserId]);const a=await c.query('SELECT balance_points FROM loyalty_accounts WHERE customer_id=? AND id_user=? FOR UPDATE',[customer,req.loyaltyUserId]);const after=Number(a[0].balance_points)+delta;if(after<0)throw new InputError('Le solde ne peut pas devenir négatif.',409);await c.query('UPDATE loyalty_accounts SET balance_points=? WHERE customer_id=?',[after,customer]);await c.query('INSERT INTO loyalty_ledger (id,id_user,customer_id,operation_key,operation_type,points_delta,balance_after,reason) VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),req.loyaltyUserId,customer,key,'manual_adjustment',delta,after,reason])});res.json({ok:true})}catch(e){next(e)}});
r.post('/gift-cards',async(req,res,next)=>{try{const amount=money(req.body?.amount),expiry=text(req.body?.expiresAt,10);if(amount<100||amount>1000000||expiry&&!/^\d{4}-\d{2}-\d{2}$/.test(expiry))throw new InputError('Carte cadeau invalide.');const id=crypto.randomUUID(),code=`GS-${crypto.randomBytes(6).toString('hex').toUpperCase()}`;await transaction(await deps.getPool(),async c=>{await c.query('INSERT INTO gift_cards (id,id_user,code,initial_cents,balance_cents,expires_at) VALUES (?,?,?,?,?,?)',[id,req.loyaltyUserId,code,amount,amount,expiry||null]);await c.query('INSERT INTO gift_card_ledger (id,id_user,gift_card_id,operation_key,operation_type,amount_delta_cents,balance_after_cents,reason) VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),req.loyaltyUserId,id,crypto.createHash('sha256').update(id).digest('hex'),'issued',amount,amount,'Création de la carte cadeau'])});res.status(201).json({id,code,amountCents:amount})}catch(e){next(e)}});
r.post('/gift-cards/:id/disable',async(req,res,next)=>{try{const id=String(req.params.id||'');if(!/^[a-f0-9-]{36}$/i.test(id))throw new InputError('Carte invalide.');const reason=text(req.body?.reason,500,true);await transaction(await deps.getPool(),async c=>{const card=await c.query('SELECT balance_cents FROM gift_cards WHERE id=? AND id_user=? FOR UPDATE',[id,req.loyaltyUserId]);if(!card.length)throw new InputError('Carte introuvable.',404);await c.query('UPDATE gift_cards SET status="disabled" WHERE id=? AND id_user=?',[id,req.loyaltyUserId]);await c.query('INSERT INTO gift_card_ledger (id,id_user,gift_card_id,operation_key,operation_type,amount_delta_cents,balance_after_cents,reason) VALUES (?,?,?,?,?,?,?,?)',[crypto.randomUUID(),req.loyaltyUserId,id,crypto.createHash('sha256').update(`${id}:${crypto.randomUUID()}`).digest('hex'),'disabled',0,card[0].balance_cents,reason])});res.json({ok:true})}catch(e){next(e)}});
r.use((e,req,res,next)=>res.status(e.status||503).json({error:e instanceof InputError?e.message:e.code==='ER_NO_SUCH_TABLE'?'Appliquez la migration 027.':'Opération fidélité impossible.'}));return r}
module.exports={createRouter,money};
